Following is the 30 exercises of NumPy library

In [102]:
# importing libray and printing version

import numpy as np
print(np.__version__)

1.20.1


In [103]:
# creating a numpy array
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
# creating a boolean array
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [105]:
# extracting all odd numbers from array input
arr= np.arange(9)
odd_arr=arr[arr%2 == 1] # peforming elemnet wise operation
odd_arr

array([1, 3, 5, 7])

In [106]:
# replacing odd number with -1 without affectig original array
print(np.where(arr%2==1,-1,arr ))
arr # original array

[ 0 -1  2 -1  4 -1  6 -1  8]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
# replacing odd numbers with -1
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [108]:
# divide an array from middle and convert to 2d array
arr=np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
# stacking two arrays vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np. concatenate([a,b],axis=0)
# np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [110]:
# stacking two arrays horizontally
np.concatenate([a,b],axis=1)
# np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [111]:
# genrating a custom sequence
a=np.array([1,2,3])
np.concatenate([np.repeat(a,3),np.tile(a,3)],axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [112]:
# getting common items between two python arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [113]:
# removing all items from an array that are present in another array
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [114]:
# getting positions where elemnets of two arrays match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [115]:
# getting all items within a specified range
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5)&(a<10)]

array([6, 9])

In [116]:
# swapping rows in a 2d numpy array

arr = np.arange(9).reshape(3,3)

# swapping row 1 and 2
arr[[0,2,1],:]


array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [117]:
# revesing a 2d array
arr=np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [118]:
# creating an array of random numbers from 3 to 6
np.random.randint(low=3, high=6, size=(5,3)) + np.random.random((5,3))

array([[4.38194344, 4.03647606, 4.89041156],
       [5.98092086, 3.05994199, 5.89054594],
       [4.5769015 , 4.74247969, 5.63018394],
       [5.58184219, 4.02043913, 3.21002658],
       [5.54468488, 4.76911517, 5.25069523]])

In [119]:
# getting values of top n elements from an array
np.random.seed(100)
a = np.random.uniform(1,50, 20)

np.sort(a)[-5:]

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [123]:
# converting an array of arrays into a single array
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array = np.array([arr1, arr2, arr3])
print(np.array([a for arr in array for a in arr]))

[0 1 2 3 4 5 6 7 8 9]


<ipython-input-123-d7ab3261ab64>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array = np.array([arr1, arr2, arr3])


In [125]:
# ranking items in an array using numpy
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)

print(a.argsort().argsort())
print('Array: ', a)

Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [126]:
# ranking items in a multi-dimensional array
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

print(a.ravel().argsort().argsort().reshape(a.shape))


[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [128]:
# finding maximum of each row in a multideimensional array

np.random.seed(100)
a = np.random.randint(1,10, [5,3])

np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [130]:
# finding duplicate records in a numpy array
np.random.seed(100)
a = np.random.randint(0, 5, 10)

out = np.full(a.shape[0], True)

# Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False

print(out)

[False  True False  True False False  True  True  True  True]


In [131]:
# find index of nth repition of number x in array

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

np.where(x == 1)[0][n-1]

8